baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Julsida'
theme = 'ananke'
SectionPagesMenu = "main"

[params]
  text_color = "dark-red"
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"